### ISSUE TITLE
package.json and tsconfig.json files are written as a single line

### ISSUE THREAD

**Issue by Dantaro** [jeanp117/ctsp#2]
When creating a project, the package.json and tsconfig.json files are written to a single line

Expected: Both json files should be printed multiline

Steps to reproduce:

1. Create a new project with any settings
2. Note that the package.json and tsconfig.json files that are written exists on a single line.

**Comment by jeanp117** [comment]
Fixed on v1.0.3

**Comment by Dantaro** [comment]
Perfect, thank you!
