### ISSUE TITLE
Generated Main file is improperly named as Main.ts.ts 

### ISSUE THREAD

**Issue by Dantaro** [jeanp117/ctsp#3]
When creating a project and choosing `main` as the entry point, the system creates a file called `main.ts.ts`

Expected: File should be named `main.ts`

Steps to reproduce

1. Create a new project using ctsp
2. Choose entry point as `main` rather than `index`
3. Complete setup
4. Note that the file has been generated with the name `main.ts.ts`, this includes in package.json

**Comment by jeanp117** [comment]
Fixed on v1.0.3

**Comment by Dantaro** [comment]
Perfect, thank you!
